"""Opt-in synthetic model probes. Run python -m app.check_models --help."""
import argparse
import asyncio
from contextlib import aclosing
import logging
import os

from app.providers.base import UnknownModelError


class ProbeFailure(ValueError):
    """Safe diagnostic text generated by our probes, never a provider response."""


def connection_plan(model, resolved, roles):
    """Deduplicate each model/capability pair, retaining the roles it covers."""
    plan = {}
    for role in roles:
        if role not in resolved:
            continue
        if role == model.Role.EMBEDDING:
            checks = ("embedding",)
        elif role == model.Role.INGEST_PLAN:
            checks = ("tools",)
        elif role in {model.Role.INGEST_WRITE, model.Role.RECALIBRATE}:
            checks = ("chat",)
        else:
            checks = ("converse", "stream")
        for check in checks:
            plan.setdefault((resolved[role], check), []).append(role)
    return plan


def _has_text(content):
    if isinstance(content, str):
        return bool(content.strip())
    if isinstance(content, list):
        return any(isinstance(block, dict) and _has_text(block.get("text")) for block in content)
    return False


async def probe(model, role, check):
    """Use the application's clients without saving usage or executing any tool."""
    prompt = "Reply with just the word OK."
    messages = [{"role": "user", "content": [{"text": prompt}]}]
    if check == "embedding":
        if not model.valid_embedding(await model.embed("A short synthetic connection test.")):
            raise ProbeFailure("No usable embedding returned; check model access, dimensions and response parsing")
    elif check in {"chat", "tools"}:
        client = model.get_chat(role, max_tokens=128, operation="")
        if check == "tools":
            tool = {"name": "connection_probe", "description": "Synthetic connectivity test; has no effects.",
                    "parameters": {"type": "object", "properties": {"value": {"type": "string"}},
                                   "required": ["value"]}}
            client = client.bind_tools([tool])
            prompt = "Call the connection_probe tool exactly once with value 'ok'. Do not answer with text."
        reply = await client.ainvoke([{"role": "user", "content": prompt}])
        if check == "tools":
            calls = getattr(reply, "tool_calls", [])
            if (len(calls) != 1 or calls[0].get("name") != "connection_probe"
                    or calls[0].get("args") != {"value": "ok"}):
                raise ProbeFailure("Model did not return the requested structured tool call")
        elif not _has_text(reply.content):
            raise ProbeFailure("No text returned")
    else:
        client = model.get_converse(role)
        if check == "converse":
            reply = await client.converse("You are a connection test.", messages, max_tokens=64, operation="")
            if not _has_text(reply):
                raise ProbeFailure("No text returned")
        elif check == "stream":
            has_text = False
            async with aclosing(client.converse_stream(
                    "You are a connection test.", messages, max_tokens=64, operation="")) as stream:
                async for chunk in stream:
                    has_text = has_text or _has_text(chunk)
            if not has_text:
                raise ProbeFailure("No streamed text returned")
        else:
            raise ValueError("Unknown connection check")


async def run_checks(model, args):
    try:
        resolved = model.validate_configuration()
    except ValueError as exc:
        # These configuration errors contain role/model names, not provider responses.
        print(f"Configuration failed: {exc}")
        return 1
    roles = [model.Role(role) for role in args.role] if args.role else list(model.Role)
    plan = connection_plan(model, resolved, roles)
    print(f"Provider: {model.provider_name()}")
    if model.Role.EMBEDDING in roles and model.Role.EMBEDDING not in resolved:
        print("SKIP embedding: disabled")
    failed = False
    for (model_id, check), covered in plan.items():
        label = f"{check}: {model_id} ({', '.join(r.value for r in covered)})"
        if not args.live:
            print(f"NOT TESTED {label}")
            continue
        try:
            await probe(model, covered[0], check)
            print(f"PASS {label}", flush=True)
        except Exception as exc:
            # Never print provider exception messages: they may contain keys or URLs.
            reason = (str(exc) if isinstance(exc, ProbeFailure) else
                      f"{type(exc).__name__}; check credentials, access, capability and response format")
            print(f"FAIL {label}: {reason}", flush=True)
            failed = True
    if not args.live:
        print("Local configuration check only; credentials and capabilities were not tested live.")
        print("Use --live --yes to send small billable synthetic requests. No wiki data is sent or changed.")
    return int(failed)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Check model configuration; live calls require explicit consent.")
    parser.add_argument("--live", action="store_true", help="Send small synthetic requests; provider charges may apply")
    parser.add_argument("--yes", action="store_true", help="Acknowledge live requests and possible charges")
    parser.add_argument("--role", action="append", choices=["ingest_plan", "ingest_write", "query",
                        "recalibrate", "draft_agent", "edit", "embedding"], help="Limit probes to this role (repeatable)")
    args = parser.parse_args(argv)
    if args.live and not args.yes:
        parser.error("--live requires --yes to acknowledge possible charges")
    if args.yes and not args.live:
        parser.error("--yes is only meaningful with --live")
    # Disable SDK logs and external tracing in this CLI process, not in the app.
    previous_level = logging.root.manager.disable
    tracing = {name: os.environ.get(name) for name in ("LANGCHAIN_TRACING_V2", "LANGSMITH_TRACING")}
    try:
        logging.disable(logging.CRITICAL)
        for name in tracing:
            os.environ[name] = "false"
        from app import model
        if args.live:
            print("Live checks may incur charges. Only synthetic prompts are sent; no database access is needed.")
        return asyncio.run(run_checks(model, args))
    except KeyboardInterrupt:
        print("Connection check interrupted.")
        return 130
    except UnknownModelError as exc:
        print(f"Configuration failed: {exc}")
        return 1
    except Exception as exc:
        print(f"Unable to run checks: {type(exc).__name__}. Check settings and installed provider dependencies.")
        return 1
    finally:
        logging.disable(previous_level)
        for name, value in tracing.items():
            if value is None:
                os.environ.pop(name, None)
            else:
                os.environ[name] = value


if __name__ == "__main__":
    raise SystemExit(main())
